tasks:
  - name: Frontend
    init: |
      nvm install 20
      npm ci
    command: |
      nvm use 20
      npm start

ports:
  - port: 3000
    name: Frontend
    description: Access the React PWA app.
    visibility: public
    onOpen: open-browser

